version: '3'
services:
  app:
    build: .
    ports:
      - "9000:9999"
    depends_on:
      - mongo
    environment:
      - mongodb://localhost:27017/
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local